# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build React

on:
 # push:
  #  branches: '**'
 workflow_dispatch:  
  #pull_request:
   # branches: '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install    
     # - name: Test
      #  run: npm test
        env:
          CI: true
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow 
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v2
        with:
          name: react-github-actions-build
          path: build
       #   env:
        #    CD:true
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
         HOST: ${{ secrets.SERVER_IP_ADDRESS }}
         USERNAME: ${{ secrets.SERVER_USERNAME }}
         KEY: ${{ secrets.KEY }}
         PORT: 22
         script: |
          sudo apt-get -y update
          sudo apt-get -y install nginx

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
                 HOST: ${{ secrets.SERVER_IP_ADDRESS }}        
                 USERNAME: ${{ secrets.SERVER_USERNAME }}      
                 KEY: ${{ secrets.KEY}}
                 PORT: 22
        with:
                source: '.'
                target: '~/.'
