name: Deploy React

on:
 # push:
  #  branches: '**'
 workflow_dispatch:  
  #pull_request:
   # branches: '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install    
     # - name: Test
      #  run: npm test
        env:
          CI: true
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow 


      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
                 HOST: ${{ secrets.IP_ADDRESS_FE }}        
                 USERNAME: ${{ secrets.SERVER_USERNAME }}      
                 KEY: ${{ secrets.KEY }}
                 PORT: 22
        with:
                source: './build'
                target: '.'

      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
         HOST: ${{ secrets.IP_ADDRESS_FE }}
         USERNAME: ${{ secrets.SERVER_USERNAME }}
         KEY: ${{ secrets.KEY }}
         PORT: 22
         script: |
          sudo apt-get -y update 
          sudo apt -y install apache2
 #        sudo cp -RT /home/azureuser/build /var/www/html
 #         sudo rm -r build
